name: CI Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to deploy from"
        required: true
        default: "develop"
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch_name || 'develop' }}

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ env.DOCKER_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build . -t ${{ env.DOCKER_REGISTRY}}${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER}:dev-${{ github.sha }}
        
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_REGISTRY}}${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER}:dev-${{ github.sha }}
        
      - name: Deploy to Dev
        run: |
          echo "Desplegando imagen ${{ env.DOCKER_REGISTRY}}${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER}:dev-${{ github.sha }} a entorno de desarrollo"
          # Aquí añadirías tus pasos reales de despliegue a EKS (kubectl, helm, etc.)
        
