name: CI Build

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME: 
        description: "Docker username"
        required: true
      DOCKER_PASSWORD:
        description: "Docker password"
        required: true
    inputs:
      docker_registry:
        type: string
        description: "Docker registry"
        required: true
      image_name:
        type: string
        description: "Image name"
        required: true
      tag:
        type: string
        description: "Tag"
        required: true
      should_be_inmutable:
        description: "Should be inmutable"
        required: false
        default: false
        type: boolean

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env:
            DOCKER_REGISTRY: ${{ inputs.docker_registry }}
            DOCKER_USERNAME: ${{ secrets.docker_username }}
            DOCKER_PASSWORD: ${{ secrets.docker_password }}
        steps:
            - name: Docker login
              run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
        
            - name: Check if the image already exists
              if: ${{ inputs.should_be_inmutable == true }}
              run: |
                echo "Checking if the image $DOCKER_REGISTRY/$IMAGE_NAME:$TAG already exists"
                docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
                echo "Image $DOCKER_REGISTRY/$IMAGE_NAME:$TAG already exists"
                exit 1

            - name: Build Docker image
              run: |
                echo "Building Docker image $DOCKER_REGISTRY/$IMAGE_NAME:$TAG"
                docker build . -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG
                
            - name: Push Docker image
              run: docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG