name: CI Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to deploy from"
        required: true
        default: "develop"
        type: string

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.set-image-url.outputs.IMAGE_URL }}
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      # - name: Dump job context
      #   env:
      #     JOB_CONTEXT: ${{ toJson(job) }}
      #   run: echo "$JOB_CONTEXT"
      
      - name: Set dynamic env variables
        id: set-image-url
        run: |
          export BRANCH_NAME=$(echo ${{ github.ref }} | cut -d '/' -f 3)
          export REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          export IMAGE_URL=$DOCKER_REGISTRY/$DOCKER_USERNAME/$REPOSITORY_NAME:$BRANCH_NAME-${{ github.sha }}
          echo $IMAGE_URL
          echo "IMAGE_URL=$IMAGE_URL"  >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch_name || env.BRANCH_NAME }}
    
  build-and-push:
    secrets: inherit
    needs: initialize
    uses: axprueba/branching/.github/workflows/ci_build.yml@develop
    with:
      image_url: ${{ needs.initialize.outputs.image_url }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dump GitHub context
        run: echo "Desplegando imagen $IMAGE_URL a entorno de desarrollo"