name: CI Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to deploy from"
        required: true
        default: "develop"
        type: string
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRON_VARIABLE: ${{ vars.ENVIRON_VARIABLE }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: "badiolajulen/branching"
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch_name || 'develop' }}

      - name: Set tag
        id: set-tag
        run: echo "tag=${GITHUB_REF##*/}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        uses: axprueba/workflows/actions/docker-build-push@master
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.set-tag.outputs.tag }}
          
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dump GitHub context
        run: echo "Desplegando imagen 'badiolajulen/branching:${{ needs.build.outputs.tag }}' a entorno de desarrollo"