name: CI Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to deploy from"
        required: true
        default: "develop"
        type: string
    

env:
  IMAGE_NAME: badiolajulen/branching
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "${{ vars.ENVIRON_VARIABLE }}"
          echo "${{ vars.IMAGE_NAME }}"

      - name: Push Docker image
        uses: axprueba/branching/.github/workflows/ci_build.yml@develop
        with:
          docker_registry: ${{ vars.DOCKER_REGISTRY }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ vars.IMAGE_NAME }}
          tag: ${{ github.ref }}-${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dump GitHub context
        run: echo "Desplegando imagen '${{ env.IMAGE_NAME }}:${{ github.ref }}-${{ github.sha }}' a entorno de desarrollo"