name: CI Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to deploy from"
        required: true
        default: "develop"
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      
      - name: Set dynamic env variables
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
          echo "IMAGE_URL=${{ env.DOCKER_REGISTRY }}/$DOCKER_USERNAME/${{ env.REPOSITORY_NAME}}:${{ env.BRANCH_NAME }}-${{ github.sha }}"  >> $GITHUB_ENV
          
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch_name || env.BRANCH_NAME }}

      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ${{ env.DOCKER_REGISTRY }}

      - name: Build Docker image
        run: |
          echo "Building Docker image $IMAGE_URL"
          docker build . -t $IMAGE_URL
        
      - name: Push Docker image
        run: docker push $IMAGE_URL
        
      - name: Deploy to Dev
        run: |
          echo "Desplegando imagen $IMAGE_URL a entorno de desarrollo"
        
