name: CI Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to deploy from"
        required: true
        default: "develop"
        type: string
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRON_VARIABLE: ${{ vars.ENVIRON_VARIABLE }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: "badiolajulen/branching"
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch_name || 'develop' }}
          
      - name: Debug
        run: |
          echo "${{ vars.ENVIRON_VARIABLE }}"
          echo "${{ vars.IMAGE_NAME }}"

      - name: Set tag
        id: set-tag
        run: echo "tag=${GITHUB_REF##*/}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY

      - name: Build Docker image
        run: |
          echo "Building Docker image $DOCKER_REGISTRY/$IMAGE_NAME:${{ steps.set-tag.outputs.tag }}"
          docker build . -t $DOCKER_REGISTRY/$IMAGE_NAME:${{ steps.set-tag.outputs.tag }}
          
      - name: Push Docker image
        run: docker push $DOCKER_REGISTRY/$IMAGE_NAME:${{ steps.set-tag.outputs.tag }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dump GitHub context
        run: echo "Desplegando imagen 'badiolajulen/branching:${{ needs.build.outputs.tag }}' a entorno de desarrollo"