name: CI Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  retag-image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Solo si fue mergeado
    env:
      ENVIRON_VARIABLE: ${{ vars.ENVIRON_VARIABLE }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: "badiolajulen/branching"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get version from VERSION
        id: get-version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if production docker image exists
        uses: axprueba/workflows/actions/docker-check-if-image-exists@master
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          tag: ${{ env.VERSION }}
          
      - name: Extraer versión y tipo de rama
        run: |
          BRANCH_REF="${{ github.event.pull_request.head.ref }}"
          echo "Head ref (rama origen del PR) es: $BRANCH_REF"

          if [[ "$BRANCH_REF" =~ ^release/ ]]; then
            TAG_SUFFIX="-rc"

          elif [[ "$BRANCH_REF" =~ ^hotfix/ ]]; then
            TAG_SUFFIX="-hotfix"

          else
            echo "No es una rama release/* ni hotfix/* => no se extrae versión"
            exit 1
          fi
          echo "TAG_SUFFIX=$TAG_SUFFIX" >> $GITHUB_ENV

      - name: Add latest tag to image
        uses: axprueba/workflows/actions/docker-retag@master
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          old_tag: ${{ vars.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.VERSION }}${{ env.TAG_SUFFIX }}
          new_tag: ${{ vars.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.VERSION }}

      - name: Deploy to Production
        run: |
          echo "Desplegando imagen $NEW_TAG a entorno de producción"