name: CI Hotfix & Release

on:
  push:
    branches:
      - "release/*"
      - "hotfix/*"
  pull_request:
    branches:
      - "release/*"
      - "hotfix/*"
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRON_VARIABLE: ${{ vars.ENVIRON_VARIABLE }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: "badiolajulen/branching"
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extraer versión y tipo de rama
        id: set-tag
        run: |
          BRANCH_REF="${{ github.ref_name }}"
          echo "Branch ref: $BRANCH_REF"

          if [[ "$BRANCH_REF" =~ ^release/ ]]; then
            TAG="${BRANCH_REF#release/}-rc-${{ github.sha }}"
            LATEST_TAG="${BRANCH_REF#release/}-rc"
          elif [[ "$BRANCH_REF" =~ ^hotfix/ ]]; then
            TAG="${BRANCH_REF#hotfix/}-hotfix-${{ github.sha }}"
            LATEST_TAG="${BRANCH_REF#release/}-hotfix"
          else
            echo "No es una rama release/* ni hotfix/* => Saliendo."
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # get version from VERSION.txt
      - name: Get version from VERSION.txt
        id: get-version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if production docker image exists
        uses: axprueba/workflows/actions/docker-check-if-image-exists@master
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.get-version.outputs.VERSION }}

      - name: Build & Push Docker Image
        uses: axprueba/workflows/actions/docker-build-push@master
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          tag: ${{ env.LATEST_TAG }}
          
      # - name: Add latest tag to image
      #   uses: axprueba/workflows/actions/docker-retag@master
      #   with:
      #     registry: ${{ vars.DOCKER_REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     image_name: ${{ env.IMAGE_NAME }}
      #     old_tag: ${{ env.LATEST_TAG }}
      #     new_tag: ${{ env.TAG }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dump GitHub context
        run: echo "Desplegando imagen 'badiolajulen/branching:${{ needs.build.outputs.tag }}' a entorno de desarrollo"