name: CI Hotfix & Release

on:
  pull_request:
    branches:
      - "release/*"
      - "hotfix/*"
    types: [opened, synchronize]

jobs:
  build-and-retag:
    runs-on: ubuntu-latest
    env:
      ENVIRON_VARIABLE: ${{ vars.ENVIRON_VARIABLE }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: "badiolajulen/branching"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extraer versión y tipo de rama
        id: extract_version
        run: |
          BRANCH_REF="${{ github.ref_name }}"
          echo "Branch ref: $BRANCH_REF"

          if [[ "$BRANCH_REF" =~ ^release/ ]]; then
            TAG="${BRANCH_REF#release/}-rc"
          elif [[ "$BRANCH_REF" =~ ^hotfix/ ]]; then
            TAG="${BRANCH_REF#hotfix/}-hotfix"
          else
            echo "No es una rama release/* ni hotfix/* => Saliendo."
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        uses: axprueba/workflows/actions/docker-build-push@master
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          tag: ${{ env.TAG }}